# Generated by Django 4.0.3 on 2022-04-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='5ac849de-abc6-4ec1-b7df-c9c40c95d07d', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
