# Generated by Django 4.0.3 on 2022-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_customerid_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='07e5ab8a-0907-4f1a-b0f5-1908ccf28af4', max_length=200),
        ),
    ]
