# Generated by Django 4.0.3 on 2022-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customer_dob_alter_customer_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='4f125add-500e-4e3e-874f-f249102981f8', max_length=200),
        ),
    ]
