# Generated by Django 4.0.3 on 2022-04-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customer_dob_alter_customer_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(default='5c6ce787-e427-46db-aa67-ba7d84de1df2', max_length=200),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='account_no',
            field=models.CharField(max_length=20),
        ),
    ]
