# Generated by Django 4.0.3 on 2022-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customer_customerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
