# Generated by Django 4.0.3 on 2022-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customeraccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
