# Generated by Django 4.0.3 on 2022-04-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customeraccount_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerotp',
            name='customer',
        ),
    ]
