# Generated by Django 4.0.3 on 2022-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_customerotp_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
