# Generated by Django 4.0.3 on 2022-06-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('other_bank_transfer', 'Other Bank Transfer'), ('airtime', 'Airtime'), ('data', 'Data')], default='', max_length=200)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_bank', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_acct_no', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
    ]
