# Generated by Django 4.0.3 on 2022-06-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='biller_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('other_bank_transfer', 'Other Bank Transfer'), ('airtime', 'Airtime'), ('data', 'Data'), ('utility', 'Utility')], default='', max_length=200),
        ),
    ]
