# Generated by Django 4.0.3 on 2022-06-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_beneficiary_options_transaction_benefiary_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='benefiary_name',
            new_name='beneficiary_name',
        ),
    ]
