# Generated by Django 4.0.3 on 2022-06-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_benefiary_name_transaction_beneficiary_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='benefiary_number',
            new_name='beneficiary_number',
        ),
    ]
