# Generated by Django 4.0.3 on 2022-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_customer_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='transfer_limit',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=20),
        ),
    ]
