# Generated by Django 4.0.3 on 2022-10-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_customer_daily_limit_customer_transfer_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('support_email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('logo', models.ImageField(upload_to='bank-logo')),
            ],
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='bank_acct_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bank'),
        ),
    ]
