# Generated by Django 4.0.3 on 2022-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_bank_customeraccount_bank_acct_number_customer_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
