# Generated by Django 4.0.3 on 2022-11-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_customeraccount_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_acct_no', models.CharField(blank=True, max_length=200, null=True)),
                ('transfer_type', models.CharField(choices=[('transfer', 'Transfer'), ('bill_payment', 'Bill Payment')], default='transfer', max_length=100)),
                ('beneficiary_type', models.CharField(blank=True, choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('other_bank_transfer', 'Other Bank Transfer'), ('airtime', 'Airtime')], max_length=100, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_acct_no', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=100)),
                ('amount', models.FloatField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=12, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='biller_name',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('other_bank_transfer', 'Other Bank Transfer'), ('airtime', 'Airtime')], default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
