# Generated by Django 4.0.3 on 2022-11-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_customeraccount_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiary_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='biller_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_option',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_acct_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_type',
            field=models.CharField(blank=True, choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer'), ('airtime', 'Airtime'), ('data', 'Data'), ('utility', 'Utility')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_acct_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer')], default='transfer', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer'), ('airtime', 'Airtime'), ('data', 'Data'), ('utility', 'Utility')], default='', max_length=200),
        ),
    ]
