# Generated by Django 4.0.3 on 2022-12-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_transaction_beneficiary_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
    ]
