# Generated by Django 4.0.3 on 2022-11-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_transfer_remove_beneficiary_biller_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('other_bank_transfer', 'Other Bank Transfer')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='beneficiary_type',
            field=models.CharField(blank=True, choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('other_bank_transfer', 'Other Bank Transfer')], max_length=100, null=True),
        ),
    ]
