# Generated by Django 4.0.3 on 2022-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_beneficiary_beneficiary_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('cit_other_bank_transfer', 'CIT Other Bank Transfer')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='beneficiary_type',
            field=models.CharField(blank=True, choices=[('cit_bank_transfer', 'CIT Bank Transfer'), ('cit_other_bank_transfer', 'CIT Other Bank Transfer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer')], default='transfer', max_length=100),
        ),
    ]
