# Generated by Django 4.0.3 on 2022-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_customer_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer')], default='local_transfer', max_length=100),
        ),
    ]
