# Generated by Django 4.0.3 on 2022-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_transaction_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='tm_service_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
