# Generated by Django 4.0.3 on 2022-12-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
    ]
