# Generated by Django 4.0.3 on 2022-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_accountrequest_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bill_payment_charges',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
    ]
