# Generated by Django 4.0.3 on 2023-01-04 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_bank_bill_payment_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='auth_key_bank_flex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='enquiry_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='feedback_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='institution_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='mfb_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='officer_rating_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='registration_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
