# Generated by Django 4.0.3 on 2023-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_bank_auth_key_bank_flex_bank_auth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
