# Generated by Django 4.0.3 on 2023-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_bank_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bank-logo'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='support_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
