# Generated by Django 4.0.3 on 2023-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_bank_address_alter_bank_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='app_version',
            field=models.IntegerField(default=1),
        ),
    ]
