# Generated by Django 4.0.3 on 2023-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_bank_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='tm_notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
