# Generated by Django 4.0.3 on 2023-02-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_bank_tm_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='settlement_acct_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
