# Generated by Django 4.0.3 on 2023-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_bank_settlement_acct_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='savings_product_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
