# Generated by Django 4.0.3 on 2023-03-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0004_institution_customerid_mandate_otp_and_more'),
        ('account', '0041_alter_bank_savings_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_acct_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.transferrequest'),
        ),
    ]
