# Generated by Django 4.0.3 on 2023-04-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0009_bulktransferrequest_decline_reason_and_more'),
        ('account', '0042_transaction_institution_transaction_sender_acct_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer'),
        ),
    ]
