# Generated by Django 4.0.3 on 2023-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_bank_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='product_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
