# Generated by Django 4.0.3 on 2023-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_customeraccount_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='non_required_codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
