# Generated by Django 4.0.3 on 2023-07-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_bank_non_required_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='dispute_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
