# Generated by Django 4.0.3 on 2023-10-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_bank_dispute_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='transfer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
