# Generated by Django 4.0.3 on 2023-11-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bank_transfer_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='payattitude_client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer'), ('airtime', 'Airtime'), ('data', 'Data'), ('utility', 'Utility'), ('payattitude', 'Payattitude')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary_type',
            field=models.CharField(blank=True, choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer'), ('airtime', 'Airtime'), ('data', 'Data'), ('utility', 'Utility'), ('payattitude', 'Payattitude')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('external_transfer', 'External Transfer'), ('payattitude', 'Payattitude')], default='local_transfer', max_length=100),
        ),
    ]
