# Generated by Django 4.0.3 on 2024-01-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_transaction_channel_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='customer_onboarding_type',
            field=models.CharField(choices=[('no_verify', 'No Verify'), ('admin_verify', 'Admin Verify'), ('liveness_verify', 'Liveness Verify')], default='admin_verify', max_length=90),
        ),
        migrations.AddField(
            model_name='bank',
            name='tier_account_system',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], default='tier_1', max_length=100)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=50000, max_digits=20)),
                ('transfer_limit', models.DecimalField(decimal_places=2, default=20000, max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.accounttier'),
        ),
    ]
