# Generated by Django 4.0.3 on 2024-01-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_tierupgraderequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivenessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='liveness_images')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bank')),
            ],
        ),
    ]
