# Generated by Django 4.0.3 on 2024-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_livenessimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('payattitude-charged', 'Payattitude Charged')], default='pending', max_length=100),
        ),
    ]
