# Generated by Django 4.0.3 on 2024-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='payattitude_settlement_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
