# Generated by Django 4.0.3 on 2024-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_bank_payattitude_settlement_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayattitudeSettlementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('response', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='payattitude_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
