# Generated by Django 4.0.3 on 2024-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_payattitudesettlementlog_bank_payattitude_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='tm_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='tm_sms_sender_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
