# Generated by Django 4.0.3 on 2022-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpayment', '0004_electricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
