# Generated by Django 4.0.3 on 2022-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpayment', '0005_electricity_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='token_sent',
            field=models.BooleanField(default=False),
        ),
    ]
