# Generated by Django 4.0.3 on 2022-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpayment', '0006_electricity_token_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
