# Generated by Django 4.0.3 on 2022-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpayment', '0007_airtime_reference_cabletv_reference_data_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.CharField(max_length=50)),
                ('transaction_reference', models.CharField(max_length=50)),
                ('payment_type', models.CharField(default='airtime', max_length=50)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
