# Generated by Django 4.0.3 on 2022-12-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_customer_bank'),
        ('billpayment', '0009_alter_billpaymentreversal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
        migrations.AddField(
            model_name='billpaymentreversal',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
        migrations.AddField(
            model_name='data',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bank'),
        ),
    ]
