# Generated by Django 4.0.3 on 2023-03-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billpayment', '0010_airtime_bank_billpaymentreversal_bank_cabletv_bank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricity',
            options={'verbose_name_plural': 'Electricity'},
        ),
    ]
