# Generated by Django 4.0.3 on 2023-04-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0009_bulktransferrequest_decline_reason_and_more'),
        ('billpayment', '0011_alter_electricity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airtime',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airtime',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='airtime',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution'),
        ),
        migrations.AddField(
            model_name='airtime',
            name='response_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='airtime',
            name='transaction_option',
            field=models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='airtime',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='airtime',
            name='transaction_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='airtime',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution'),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='response_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='transaction_option',
            field=models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='transaction_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution'),
        ),
        migrations.AddField(
            model_name='data',
            name='response_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='transaction_option',
            field=models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='transaction_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='response_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='transaction_option',
            field=models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='electricity',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='electricity',
            name='transaction_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='electricity',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
