# Generated by Django 4.0.3 on 2023-04-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0010_bulktransferrequest_amount'),
        ('billpayment', '0012_airtime_approved_airtime_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('checked', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=100)),
                ('decline_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution')),
            ],
        ),
        migrations.AddField(
            model_name='airtime',
            name='bulk_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billpayment.bulkbillpayment'),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='bulk_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billpayment.bulkbillpayment'),
        ),
        migrations.AddField(
            model_name='data',
            name='bulk_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billpayment.bulkbillpayment'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='bulk_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billpayment.bulkbillpayment'),
        ),
    ]
