# Generated by Django 4.0.3 on 2023-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0018_alter_limit_daily_limit_alter_limit_transfer_limit'),
        ('billpayment', '0013_bulkbillpayment_airtime_bulk_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='airtime_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='airtime',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='airtime_declined', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='bulkbillpayment',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='bulk_bill_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='bulkbillpayment',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='bulk_bill_declined', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='cable_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='cabletv',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='cable_declined', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='data',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='data_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='data',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='data_declined', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='elect_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='elect_declined', to='coporate.mandate'),
        ),
    ]
