# Generated by Django 4.0.3 on 2023-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpayment', '0014_airtime_approved_by_airtime_declined_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkbillpayment',
            name='payment_type',
            field=models.CharField(default='airtime', max_length=200),
        ),
    ]
