# Generated by Django 4.0.3 on 2023-03-12 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mandate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandate_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
