# Generated by Django 4.0.3 on 2023-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0002_institution_created_by_mandate_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='bvn',
            field=models.TextField(),
        ),
    ]
