# Generated by Django 4.0.3 on 2023-03-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0003_alter_mandate_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='customerID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='transaction_pin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=60)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('transfer_type', models.CharField(max_length=20)),
                ('beneficiary_acct', models.CharField(max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('nip_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_acct_type', models.CharField(blank=True, max_length=20, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=200000, max_digits=20)),
                ('transfer_limit', models.DecimalField(decimal_places=2, default=100000, max_digits=20)),
                ('checked', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coporate.institution')),
            ],
        ),
    ]
