# Generated by Django 4.0.3 on 2023-03-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0004_institution_customerid_mandate_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='pin_set',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='transaction_pin',
        ),
    ]
