# Generated by Django 4.0.3 on 2023-03-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0006_transferscheduler_transferrequest_decline_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('used', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coporate.institution')),
            ],
        ),
    ]
