# Generated by Django 4.0.3 on 2023-04-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0008_transferrequest_transfer_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferrequest',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulktransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=100),
        ),
    ]
