# Generated by Django 4.0.3 on 2023-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0009_bulktransferrequest_decline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferrequest',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
