# Generated by Django 4.0.3 on 2023-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0010_bulktransferrequest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='role',
        ),
        migrations.AddField(
            model_name='mandate',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
