# Generated by Django 4.0.3 on 2023-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0011_remove_mandate_role_mandate_level_delete_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrequest',
            old_name='account_number',
            new_name='account_no',
        ),
    ]
