# Generated by Django 4.0.3 on 2023-05-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0012_rename_account_number_transferrequest_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='trans_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='trans_declined', to='coporate.mandate'),
        ),
    ]
