# Generated by Django 4.0.3 on 2023-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0014_bulktransferrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
