# Generated by Django 4.0.3 on 2023-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0015_alter_mandate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferscheduler',
            name='transfer_option',
            field=models.CharField(choices=[('single', 'Single'), ('bulk', 'Bulk')], default='single', max_length=50),
        ),
    ]
