# Generated by Django 4.0.3 on 2023-05-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0016_transferscheduler_transfer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
