# Generated by Django 4.0.3 on 2023-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0017_alter_mandate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='limit',
            name='transfer_limit',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=20),
        ),
    ]
