# Generated by Django 4.0.3 on 2023-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coporate', '0018_alter_limit_daily_limit_alter_limit_transfer_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='limit_approved', to='coporate.mandate'),
        ),
        migrations.AddField(
            model_name='limit',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='limit_declined', to='coporate.mandate'),
        ),
    ]
